{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "5.3.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-5.3.20.jar",
          "url": "spring-jcl-5.3.20.jar",
          "size": 24437,
          "sha512": "68985f896d620245d2ffd197525bab65b4cb5941108f4db1b3cf7ec6fcf0246367b7fdb1164da052876af4efce42caeae13c4bcffa634b9c54d0fcd37ef04dfd",
          "sha256": "fb6c6bf524b19a03103812e0104eaf0bcbc178ae8f425db8b547963b13483e28",
          "sha1": "35119231d09863699567ce579c21512ddcbc5407",
          "md5": "5960098d2253e57c262e243b996de56f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-5.3.20.jar",
          "url": "spring-jcl-5.3.20.jar",
          "size": 24437,
          "sha512": "68985f896d620245d2ffd197525bab65b4cb5941108f4db1b3cf7ec6fcf0246367b7fdb1164da052876af4efce42caeae13c4bcffa634b9c54d0fcd37ef04dfd",
          "sha256": "fb6c6bf524b19a03103812e0104eaf0bcbc178ae8f425db8b547963b13483e28",
          "sha1": "35119231d09863699567ce579c21512ddcbc5407",
          "md5": "5960098d2253e57c262e243b996de56f"
        }
      ]
    }
  ]
}
